# Pescaru Tudor-Mihai 321CA 2021
FLAGS=-Wall -Wextra -std=c++17

build:
	g++	$(FLAGS) crypto.cpp -o crypto
	g++ $(FLAGS) stocks.cpp -o stocks
	g++ $(FLAGS) valley.cpp -o valley
	g++ $(FLAGS) ridge.cpp -o ridge
	g++ $(FLAGS) trigigel.cpp -o trigigel
run-p1: crypto
	./crypto
run-p2: stocks
	./stocks
run-p3:
	./valley
run-p4:
	./ridge
run-p5:
	./trigigel
clean:
	rm -f crypto stocks valley ridge trigigel